version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: ${DB_NAME:-chatdb}
      POSTGRES_USER: ${DB_USER:-chatuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-chatpass}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql

  chat-backend:
    build: .
    ports:
      - '${API_PORT:-8000}:8000'
    environment:
      - PYTHONPATH=/app
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-chatdb}
      - DB_USER=${DB_USER:-chatuser}
      - DB_PASSWORD=${DB_PASSWORD:-chatpass}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-true}
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
